### ISSUE TITLE
Merge problem: "^telegraf::outputs(.*)$": merge: strategy: first

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-telegraf#106]
Hello,

I defined a global output for all hosts, except the DMZ host. My problem is, that I get two output URL in my outputs, the first one is the global (not needed), the second is the  one, I need. I use also the changes from: https://github.com/yankcrime/puppet-telegraf/pull/99

I tried to use:
```
lookup_options:
  "^telegraf::outputs(.*)$":
    merge:
      strategy: first
```
but it does not work. I get always both URLs, instead of only this one, if defined in my host.yaml.

We use the same for the "apt" class, and this works as expected.  What I have done wrong ?

Any suggestions ?
