### ISSUE TITLE
Is there a way to set up multiple discreet influxdb outputs?

### ISSUE THREAD

**Issue by greenaar** [voxpupuli/puppet-telegraf#129]
I'd like to set 2 different telegraf outputs, one tagged, one default.

When using hiera
```
telegraf::outputs:
  influxdb:
    - urls:
        - "http://sys.home.local:8086"
      database: 'telegraf'
      skip_database_creation: false
```
The title is also the output type.  I didn't see an easy way to change that, I'd expect

```
telegraf::outputs:
  influxdb:
    - urls:
        - "http://sys.home.local:8086"
      database: 'telegraf'
      skip_database_creation: false
  influxdb_other:
    plugin_type: 'influxdb'
    - urls:
        - "http://sys.home.local:8086"
      database: 'data'
      skip_database_creation: false
```
would work, but it doesn't (bad yaml).  Do you have an example using hiera with 2 different outputs?

**Comment by greenaar** [comment]
Turns out the answer i needed looks like this:

```
telegraf::outputs:
  influxdb:
    - urls:
        - "http://sys.home.local:8086"
      database: 'telegraf'
      skip_database_creation: false
      tagdrop:
        influxdb_database:
          - '*'
    - urls:
        - "http://sys.home.local:8086"
      database: 'syslog'
      skip_database_creation: false
      tagpass:
        influxdb_database:
          - 'syslog'
```
