### ISSUE TITLE
Cannot use multifile plugin 

### ISSUE THREAD

**Issue by kanbara** [voxpupuli/puppet-telegraf#177]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: v5.5.10
- Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
- Distribution: Ubuntu focal 20.04
- Module version: unusure

## How to reproduce (e.g Puppet code you use)

The following YAML

```yaml
telegraf::inputs:
  multifile:
    - base_dir: "/sys/class/thermal"
  multifile.file:
    - file: "thermal_zone2/temp"
      dest: "pch_skylake"
      conversion: "float(3)"
    - file: "thermal_zone3/temp"
      dest: "x86_pkg_temp"
      conversion: "float(3)"
```

converts to

```ini
[[inputs.multifile]]
base_dir = "/sys/class/thermal"
[[inputs."multifile.file"]]
file = "thermal_zone2/temp"
dest = "pch_skylake"
conversion = "float(3)"
[[inputs."multifile.file"]]
file = "thermal_zone3/temp"
```

## What behaviour did you expect instead

I would expect to be able to use `multifile.file` in the appropriate way. Telegraf does not startup with quotes in the config. I'm unsure what has to happen on the YAML side to use this module correctly. Using inputs.temp puts too much data points and unwanted sensors that are not as easy to work with. Otherwise, I suppose I could use two file modules, though multifile seemed to fit and converts will from 1000 -> 1.000
