### ISSUE TITLE
Correct hiera Syntax for telegraf::processors (with pull request #139)

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-telegraf#179]
Hallo,

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.22-1stretch
- Ruby: 1:2.3.3
- Distribution: Debian Stretch
- Module version:  3.1.0

## How to reproduce (e.g Puppet code you use)
```
[...]
telegraf::processors:
  enum:
    - mapping:
        "field": "tx_sqltype"
        default: 1
        'value_mappings':
          select: "0"
          update: "1"
          insert: "2"
```
## What are you seeing
```
 # PROCESSORS:
 #
 [[processors.enum]]
-[[processors.enum.mapping]]
+[processors.enum.mapping]
 default = 1
 field = "tx_sqltype"
 [processors.enum.mapping.value_mappings]
 insert = "2"
 select = "0"
 update = "1"
+
```

## What behaviour did you expect instead

No changes

## Any additional information you'd like to impart

I used the Puppet requests from   https://github.com/voxpupuli/puppet-telegraf/pull/139 but with a different template:

```
[...]
#
# PROCESSORS:
#
<%= require 'toml-rb'; TomlRB.dump({'processors'=>@processors}) %>
(END)
```

I have no idea .. how to get the correct syntax working :-)

**Comment by linuxmail** [comment]
Just solved it :-)

```
telegraf::processors:
  enum:
    -
      mapping:
        - default: 1
          "field": "tx_sqltype"
          'value_mappings':
            select: "0"
            update: "1"
            insert: "2"
```
Syntax drive me always nuts ...
