### ISSUE TITLE
Ability to handle duplicate sections

### ISSUE THREAD

**Issue by Wernervdmerwe** [voxpupuli/puppet-telegraf#85]
Agreeably this hurts the head to ponder, but seems it is a valid use case in eg [https://github.com/influxdata/telegraf/tree/master/plugins/inputs/postgresql_extensible]

If duplicates are specified as below, only the last is affected into the final configuration file

```
    sections       => {
      'postgresql_extensible.query' => {
      'sqlquery'   => 'SELECT * FROM pg_stat_database where datname',
      'version'    => 901,
      'withdbname' => true,
      'tagvalue'   => 'postgres'
      },
      'postgresql_extensible.query' => {
      'sqlquery'   => 'SELECT * FROM pg_stat_bgwriter where datname',
      'version'    => 901,
      'withdbname' => true,
      'tagvalue'   => 'postgres'
      },
    }

```

**Comment by spjmurray** [comment]
Sounds like a simple job of allowing a hash or list of hashes under the section key to me. If a hash emit, if a list duplicate the key and emit, winner winner chicken dinner.  My 50 cents...

**Comment by spjmurray** [comment]
```yaml
dog:
  name: 'scruffy' 
  breed: 'scotty' 
cat:
  - name: 'tiddles' 
    breed: 'siamese'
  - name: 'puss' 
    breed: 'ocelot' 
```
```
[dog]
name = scruffy
breed = scotty
[cat]
name = tiddles
breed = siamese
[cat]
name = puss
breed = ocelot
```
